// Generated by https://quicktype.io

export interface FrogmeStores {
    data:  Datum[];
    meta:  Meta;
    links: FrogmeStoresLinks;
}

export interface Datum {
    id:            string;
    type:          DatumType;
    attributes:    Attributes;
    links:         DatumLinks;
    relationships: Relationships;
}

export interface Attributes {
    name:         string;
    code:         string;
    active:       boolean;
    full_address: string;
    coordinates:  Coordinates;
    created_at:   string;
}

export interface Coordinates {
    latitude:  number;
    longitude: number;
}

export interface DatumLinks {
    self: string;
}

export interface Relationships {
    brands: Brands;
    zones:  Brands;
}

export interface Brands {
    data: Data | null;
}

export interface Data {
    id:   string;
    type: DataType;
}

export enum DataType {
    Brands = "brands",
    Zones = "zones",
}

export enum DatumType {
    Stores = "stores",
}

export interface FrogmeStoresLinks {
    prev:  null;
    next:  string;
    first: string;
    last:  string;
    self:  string;
}

export interface Meta {
    pagination: Pagination;
}

export interface Pagination {
    current_page: number;
    total:        number;
    per_page:     number;
}
